//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 02:05:37 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.util.get_active_staff;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.stinkbird.helpspot.private_api.response_for.util.get_active_staff package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FNotifyEmail2_QNAME = new QName("", "fNotifyEmail2");
    private final static QName _SPhone_QNAME = new QName("", "sPhone");
    private final static QName _IRequestHistoryLimit_QNAME = new QName("", "iRequestHistoryLimit");
    private final static QName _FDeleted_QNAME = new QName("", "fDeleted");
    private final static QName _SWorkspaceDefault_QNAME = new QName("", "sWorkspaceDefault");
    private final static QName _SFname_QNAME = new QName("", "sFname");
    private final static QName _XPersonPhotoId_QNAME = new QName("", "xPersonPhotoId");
    private final static QName _XSMSService_QNAME = new QName("", "xSMSService");
    private final static QName _TSignatureHTML_QNAME = new QName("", "tSignature_HTML");
    private final static QName _TSignature_QNAME = new QName("", "tSignature");
    private final static QName _SHTMLEditor_QNAME = new QName("", "sHTMLEditor");
    private final static QName _FNotifySMSUrgent_QNAME = new QName("", "fNotifySMSUrgent");
    private final static QName _Fullname_QNAME = new QName("", "fullname");
    private final static QName _SLname_QNAME = new QName("", "sLname");
    private final static QName _FNotifySMS_QNAME = new QName("", "fNotifySMS");
    private final static QName _FHideWysiwyg_QNAME = new QName("", "fHideWysiwyg");
    private final static QName _FNotifyNewRequest_QNAME = new QName("", "fNotifyNewRequest");
    private final static QName _XPerson_QNAME = new QName("", "xPerson");
    private final static QName _FUserType_QNAME = new QName("", "fUserType");
    private final static QName _FDefaultToPublic_QNAME = new QName("", "fDefaultToPublic");
    private final static QName _FDefaultTTOpen_QNAME = new QName("", "fDefaultTTOpen");
    private final static QName _FNotifyEmail_QNAME = new QName("", "fNotifyEmail");
    private final static QName _SEmail_QNAME = new QName("", "sEmail");
    private final static QName _XPersonOutOfOffice_QNAME = new QName("", "xPersonOutOfOffice");
    private final static QName _TMobileSignature_QNAME = new QName("", "tMobileSignature");
    private final static QName _FReturnToReq_QNAME = new QName("", "fReturnToReq");
    private final static QName _FHideImages_QNAME = new QName("", "fHideImages");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.stinkbird.helpspot.private_api.response_for.util.get_active_staff
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link SSMS }
     * 
     */
    public SSMS createSSMS() {
        return new SSMS();
    }

    /**
     * Create an instance of {@link Staff }
     * 
     */
    public Staff createStaff() {
        return new Staff();
    }

    /**
     * Create an instance of {@link SEmail2 }
     * 
     */
    public SEmail2 createSEmail2() {
        return new SEmail2();
    }

    /**
     * Create an instance of {@link SUsername }
     * 
     */
    public SUsername createSUsername() {
        return new SUsername();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fNotifyEmail2")
    public JAXBElement<BigInteger> createFNotifyEmail2(BigInteger value) {
        return new JAXBElement<BigInteger>(_FNotifyEmail2_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sPhone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSPhone(String value) {
        return new JAXBElement<String>(_SPhone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iRequestHistoryLimit")
    public JAXBElement<BigInteger> createIRequestHistoryLimit(BigInteger value) {
        return new JAXBElement<BigInteger>(_IRequestHistoryLimit_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fDeleted")
    public JAXBElement<BigInteger> createFDeleted(BigInteger value) {
        return new JAXBElement<BigInteger>(_FDeleted_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sWorkspaceDefault")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSWorkspaceDefault(String value) {
        return new JAXBElement<String>(_SWorkspaceDefault_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sFname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSFname(String value) {
        return new JAXBElement<String>(_SFname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPersonPhotoId")
    public JAXBElement<BigInteger> createXPersonPhotoId(BigInteger value) {
        return new JAXBElement<BigInteger>(_XPersonPhotoId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xSMSService")
    public JAXBElement<BigInteger> createXSMSService(BigInteger value) {
        return new JAXBElement<BigInteger>(_XSMSService_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tSignature_HTML")
    public JAXBElement<String> createTSignatureHTML(String value) {
        return new JAXBElement<String>(_TSignatureHTML_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tSignature")
    public JAXBElement<String> createTSignature(String value) {
        return new JAXBElement<String>(_TSignature_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sHTMLEditor")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSHTMLEditor(String value) {
        return new JAXBElement<String>(_SHTMLEditor_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fNotifySMSUrgent")
    public JAXBElement<BigInteger> createFNotifySMSUrgent(BigInteger value) {
        return new JAXBElement<BigInteger>(_FNotifySMSUrgent_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fullname")
    public JAXBElement<String> createFullname(String value) {
        return new JAXBElement<String>(_Fullname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sLname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSLname(String value) {
        return new JAXBElement<String>(_SLname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fNotifySMS")
    public JAXBElement<BigInteger> createFNotifySMS(BigInteger value) {
        return new JAXBElement<BigInteger>(_FNotifySMS_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fHideWysiwyg")
    public JAXBElement<BigInteger> createFHideWysiwyg(BigInteger value) {
        return new JAXBElement<BigInteger>(_FHideWysiwyg_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fNotifyNewRequest")
    public JAXBElement<BigInteger> createFNotifyNewRequest(BigInteger value) {
        return new JAXBElement<BigInteger>(_FNotifyNewRequest_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPerson")
    public JAXBElement<BigInteger> createXPerson(BigInteger value) {
        return new JAXBElement<BigInteger>(_XPerson_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fUserType")
    public JAXBElement<BigInteger> createFUserType(BigInteger value) {
        return new JAXBElement<BigInteger>(_FUserType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fDefaultToPublic")
    public JAXBElement<BigInteger> createFDefaultToPublic(BigInteger value) {
        return new JAXBElement<BigInteger>(_FDefaultToPublic_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fDefaultTTOpen")
    public JAXBElement<BigInteger> createFDefaultTTOpen(BigInteger value) {
        return new JAXBElement<BigInteger>(_FDefaultTTOpen_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fNotifyEmail")
    public JAXBElement<BigInteger> createFNotifyEmail(BigInteger value) {
        return new JAXBElement<BigInteger>(_FNotifyEmail_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sEmail")
    public JAXBElement<String> createSEmail(String value) {
        return new JAXBElement<String>(_SEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPersonOutOfOffice")
    public JAXBElement<BigInteger> createXPersonOutOfOffice(BigInteger value) {
        return new JAXBElement<BigInteger>(_XPersonOutOfOffice_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tMobileSignature")
    public JAXBElement<String> createTMobileSignature(String value) {
        return new JAXBElement<String>(_TMobileSignature_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fReturnToReq")
    public JAXBElement<BigInteger> createFReturnToReq(BigInteger value) {
        return new JAXBElement<BigInteger>(_FReturnToReq_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fHideImages")
    public JAXBElement<BigInteger> createFHideImages(BigInteger value) {
        return new JAXBElement<BigInteger>(_FHideImages_QNAME, BigInteger.class, null, value);
    }

}
