//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 02:04:50 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.user.get_filters;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}takeit"/>
 *           &lt;sequence>
 *             &lt;element ref="{}isunread"/>
 *             &lt;element ref="{}view"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element ref="{}fOpenedVia"/>
 *         &lt;element ref="{}fOpen" minOccurs="0"/>
 *         &lt;element ref="{}fullname"/>
 *         &lt;element ref="{}reqsummary"/>
 *         &lt;choice>
 *           &lt;element ref="{}age"/>
 *           &lt;element ref="{}dtGMTOpened"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "takeit",
    "isunread",
    "view",
    "fOpenedVia",
    "fOpen",
    "fullname",
    "reqsummary",
    "age",
    "dtGMTOpened"
})
@XmlRootElement(name = "displayColumns")
public class DisplayColumns implements Serializable {

	private static final long serialVersionUID = 7323139963113767326L;
	
	protected Takeit takeit;
    protected Isunread isunread;
    protected View view;
    @XmlElement(required = false)
    protected String fOpenedVia;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fOpen;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fullname;
    @XmlElement(required = false)
    protected String reqsummary;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String age;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dtGMTOpened;

    /**
     * Gets the value of the takeit property.
     * 
     * @return
     *     possible object is
     *     {@link Takeit }
     *     
     */
    public Takeit getTakeit() {
        return takeit;
    }

    /**
     * Sets the value of the takeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Takeit }
     *     
     */
    public void setTakeit(Takeit value) {
        this.takeit = value;
    }

    /**
     * Gets the value of the isunread property.
     * 
     * @return
     *     possible object is
     *     {@link Isunread }
     *     
     */
    public Isunread getIsunread() {
        return isunread;
    }

    /**
     * Sets the value of the isunread property.
     * 
     * @param value
     *     allowed object is
     *     {@link Isunread }
     *     
     */
    public void setIsunread(Isunread value) {
        this.isunread = value;
    }

    /**
     * Gets the value of the view property.
     * 
     * @return
     *     possible object is
     *     {@link View }
     *     
     */
    public View getView() {
        return view;
    }

    /**
     * Sets the value of the view property.
     * 
     * @param value
     *     allowed object is
     *     {@link View }
     *     
     */
    public void setView(View value) {
        this.view = value;
    }

    /**
     * Gets the value of the fOpenedVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOpenedVia() {
        return fOpenedVia;
    }

    /**
     * Sets the value of the fOpenedVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOpenedVia(String value) {
        this.fOpenedVia = value;
    }

    /**
     * Gets the value of the fOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOpen() {
        return fOpen;
    }

    /**
     * Sets the value of the fOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOpen(String value) {
        this.fOpen = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullname(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the reqsummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqsummary() {
        return reqsummary;
    }

    /**
     * Sets the value of the reqsummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqsummary(String value) {
        this.reqsummary = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the dtGMTOpened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtGMTOpened() {
        return dtGMTOpened;
    }

    /**
     * Sets the value of the dtGMTOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtGMTOpened(String value) {
        this.dtGMTOpened = value;
    }

}
