//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 02:04:50 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.user.get_filters;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}xFilter"/>
 *         &lt;element ref="{}sFilterName"/>
 *         &lt;element ref="{}displayColumns"/>
 *         &lt;element ref="{}fGlobal"/>
 *         &lt;element ref="{}sFilterFolder"/>
 *         &lt;element ref="{}count"/>
 *         &lt;element ref="{}unread"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xFilter",
    "sFilterName",
    "displayColumns",
    "fGlobal",
    "sFilterFolder",
    "count",
    "unread"
})
@XmlRootElement(name = "filter")
public class Filter {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String xFilter;
    @XmlElement(required = true)
    protected String sFilterName;
    @XmlElement(required = true)
    protected DisplayColumns displayColumns;
    @XmlElement(required = true)
    protected BigInteger fGlobal;
    @XmlElement(required = true)
    protected String sFilterFolder;
    @XmlElement(required = true)
    protected BigInteger count;
    @XmlElement(required = true)
    protected String unread;

    /**
     * Gets the value of the xFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXFilter() {
        return xFilter;
    }

    /**
     * Sets the value of the xFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXFilter(String value) {
        this.xFilter = value;
    }

    /**
     * Gets the value of the sFilterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSFilterName() {
        return sFilterName;
    }

    /**
     * Sets the value of the sFilterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSFilterName(String value) {
        this.sFilterName = value;
    }

    /**
     * Gets the value of the displayColumns property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayColumns }
     *     
     */
    public DisplayColumns getDisplayColumns() {
        return displayColumns;
    }

    /**
     * Sets the value of the displayColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayColumns }
     *     
     */
    public void setDisplayColumns(DisplayColumns value) {
        this.displayColumns = value;
    }

    /**
     * Gets the value of the fGlobal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFGlobal() {
        return fGlobal;
    }

    /**
     * Sets the value of the fGlobal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFGlobal(BigInteger value) {
        this.fGlobal = value;
    }

    /**
     * Gets the value of the sFilterFolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSFilterFolder() {
        return sFilterFolder;
    }

    /**
     * Sets the value of the sFilterFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSFilterFolder(String value) {
        this.sFilterFolder = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the unread property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnread() {
        return unread;
    }

    /**
     * Sets the value of the unread property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnread(String value) {
        this.unread = value;
    }

}
