//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 02:04:50 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.user.get_filters;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.stinkbird.helpspot.private_api.response_for.user.get_filters package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Reqsummary_QNAME = new QName("", "reqsummary");
    private final static QName _DtGMTOpened_QNAME = new QName("", "dtGMTOpened");
    private final static QName _Count_QNAME = new QName("", "count");
    private final static QName _FOpenedVia_QNAME = new QName("", "fOpenedVia");
    private final static QName _FGlobal_QNAME = new QName("", "fGlobal");
    private final static QName _Age_QNAME = new QName("", "age");
    private final static QName _SFilterFolder_QNAME = new QName("", "sFilterFolder");
    private final static QName _SFilterName_QNAME = new QName("", "sFilterName");
    private final static QName _Unread_QNAME = new QName("", "unread");
    private final static QName _XFilter_QNAME = new QName("", "xFilter");
    private final static QName _Fullname_QNAME = new QName("", "fullname");
    private final static QName _FOpen_QNAME = new QName("", "fOpen");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.stinkbird.helpspot.private_api.response_for.user.get_filters
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Filters }
     * 
     */
    public Filters createFilters() {
        return new Filters();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link DisplayColumns }
     * 
     */
    public DisplayColumns createDisplayColumns() {
        return new DisplayColumns();
    }

    /**
     * Create an instance of {@link View }
     * 
     */
    public View createView() {
        return new View();
    }

    /**
     * Create an instance of {@link Isunread }
     * 
     */
    public Isunread createIsunread() {
        return new Isunread();
    }

    /**
     * Create an instance of {@link Takeit }
     * 
     */
    public Takeit createTakeit() {
        return new Takeit();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reqsummary")
    public JAXBElement<String> createReqsummary(String value) {
        return new JAXBElement<String>(_Reqsummary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTOpened")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDtGMTOpened(String value) {
        return new JAXBElement<String>(_DtGMTOpened_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "count")
    public JAXBElement<BigInteger> createCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_Count_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fOpenedVia")
    public JAXBElement<String> createFOpenedVia(String value) {
        return new JAXBElement<String>(_FOpenedVia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fGlobal")
    public JAXBElement<BigInteger> createFGlobal(BigInteger value) {
        return new JAXBElement<BigInteger>(_FGlobal_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "age")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAge(String value) {
        return new JAXBElement<String>(_Age_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sFilterFolder")
    public JAXBElement<String> createSFilterFolder(String value) {
        return new JAXBElement<String>(_SFilterFolder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sFilterName")
    public JAXBElement<String> createSFilterName(String value) {
        return new JAXBElement<String>(_SFilterName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "unread")
    public JAXBElement<String> createUnread(String value) {
        return new JAXBElement<String>(_Unread_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xFilter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createXFilter(String value) {
        return new JAXBElement<String>(_XFilter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fullname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFullname(String value) {
        return new JAXBElement<String>(_Fullname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fOpen")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFOpen(String value) {
        return new JAXBElement<String>(_FOpen_QNAME, String.class, null, value);
    }

}
