//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.05 at 02:30:35 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.request.get;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}xRequestHistory"/>
 *         &lt;element ref="{}xRequest"/>
 *         &lt;element ref="{}xPerson"/>
 *         &lt;element ref="{}dtGMTChange"/>
 *         &lt;element ref="{}fPublic"/>
 *         &lt;element ref="{}fInitial"/>
 *         &lt;element ref="{}fNoteIsHTML"/>
 *         &lt;element ref="{}fMergedFromRequest"/>
 *         &lt;element ref="{}tLog"/>
 *         &lt;element ref="{}tNote"/>
 *         &lt;element ref="{}tEmailHeaders"/>
 *         &lt;element ref="{}sCID"/>
 *         &lt;element ref="{}external"/>
 *         &lt;element ref="{}files"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xRequestHistory",
    "xRequest",
    "xPerson",
    "dtGMTChange",
    "fPublic",
    "fInitial",
    "fNoteIsHTML",
    "fMergedFromRequest",
    "tLog",
    "tNote",
    "tEmailHeaders",
    "scid",
    "external",
    "files"
})
@XmlRootElement(name = "item")
public class Item {

    @XmlElement(required = false)
    protected BigInteger xRequestHistory;
    @XmlElement(required = false)
    protected BigInteger xRequest;
    @XmlElement(required = false)
    protected String xPerson;
    @XmlElement(required = false)
    protected String dtGMTChange;
    @XmlElement(required = false)
    protected BigInteger fPublic;
    @XmlElement(required = false)
    protected BigInteger fInitial;
    @XmlElement(required = false)
    protected BigInteger fNoteIsHTML;
    @XmlElement(required = false)
    protected BigInteger fMergedFromRequest;
    @XmlElement(required = false)
    protected String tLog;
    @XmlElement(required = false)
    protected String tNote;
    @XmlElement(required = false)
    protected TEmailHeaders tEmailHeaders;
    @XmlElement(name = "sCID", required = false)
    protected SCID scid;
    @XmlElement(required = false)
    protected BigInteger external;
    @XmlElement(required = false)
    protected Files files;

    /**
     * Gets the value of the xRequestHistory property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXRequestHistory() {
        return xRequestHistory;
    }

    /**
     * Sets the value of the xRequestHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXRequestHistory(BigInteger value) {
        this.xRequestHistory = value;
    }

    /**
     * Gets the value of the xRequest property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXRequest() {
        return xRequest;
    }

    /**
     * Sets the value of the xRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXRequest(BigInteger value) {
        this.xRequest = value;
    }

    /**
     * Gets the value of the xPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPerson() {
        return xPerson;
    }

    /**
     * Sets the value of the xPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPerson(String value) {
        this.xPerson = value;
    }

    /**
     * Gets the value of the dtGMTChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtGMTChange() {
        return dtGMTChange;
    }

    /**
     * Sets the value of the dtGMTChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtGMTChange(String value) {
        this.dtGMTChange = value;
    }

    /**
     * Gets the value of the fPublic property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFPublic() {
        return fPublic;
    }

    /**
     * Sets the value of the fPublic property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFPublic(BigInteger value) {
        this.fPublic = value;
    }

    /**
     * Gets the value of the fInitial property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFInitial() {
        return fInitial;
    }

    /**
     * Sets the value of the fInitial property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFInitial(BigInteger value) {
        this.fInitial = value;
    }

    /**
     * Gets the value of the fNoteIsHTML property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFNoteIsHTML() {
        return fNoteIsHTML;
    }

    /**
     * Sets the value of the fNoteIsHTML property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFNoteIsHTML(BigInteger value) {
        this.fNoteIsHTML = value;
    }

    /**
     * Gets the value of the fMergedFromRequest property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFMergedFromRequest() {
        return fMergedFromRequest;
    }

    /**
     * Sets the value of the fMergedFromRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFMergedFromRequest(BigInteger value) {
        this.fMergedFromRequest = value;
    }

    /**
     * Gets the value of the tLog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTLog() {
        return tLog;
    }

    /**
     * Sets the value of the tLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTLog(String value) {
        this.tLog = value;
    }

    /**
     * Gets the value of the tNote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTNote() {
        return tNote;
    }

    /**
     * Sets the value of the tNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTNote(String value) {
        this.tNote = value;
    }

    /**
     * Gets the value of the tEmailHeaders property.
     * 
     * @return
     *     possible object is
     *     {@link TEmailHeaders }
     *     
     */
    public TEmailHeaders getTEmailHeaders() {
        return tEmailHeaders;
    }

    /**
     * Sets the value of the tEmailHeaders property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEmailHeaders }
     *     
     */
    public void setTEmailHeaders(TEmailHeaders value) {
        this.tEmailHeaders = value;
    }

    /**
     * Gets the value of the scid property.
     * 
     * @return
     *     possible object is
     *     {@link SCID }
     *     
     */
    public SCID getSCID() {
        return scid;
    }

    /**
     * Sets the value of the scid property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCID }
     *     
     */
    public void setSCID(SCID value) {
        this.scid = value;
    }

    /**
     * Gets the value of the external property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExternal() {
        return external;
    }

    /**
     * Sets the value of the external property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExternal(BigInteger value) {
        this.external = value;
    }

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link Files }
     *     
     */
    public Files getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link Files }
     *     
     */
    public void setFiles(Files value) {
        this.files = value;
    }

}
