//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:55:28 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.filter.get_column_names;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}iLastReplyBy"/>
 *         &lt;element ref="{}fOpenedVia"/>
 *         &lt;element ref="{}mailbox"/>
 *         &lt;element ref="{}fOpen"/>
 *         &lt;element ref="{}xRequest"/>
 *         &lt;element ref="{}sUserId"/>
 *         &lt;element ref="{}fullname"/>
 *         &lt;element ref="{}sLastName"/>
 *         &lt;element ref="{}sEmail"/>
 *         &lt;element ref="{}sPhone"/>
 *         &lt;element ref="{}xPersonOpenedBy"/>
 *         &lt;element ref="{}xPersonAssignedTo"/>
 *         &lt;element ref="{}xStatus"/>
 *         &lt;element ref="{}sCategory"/>
 *         &lt;element ref="{}sTitle"/>
 *         &lt;element ref="{}reqsummary"/>
 *         &lt;element ref="{}lastpublicnote"/>
 *         &lt;element ref="{}lastpublicnoteby"/>
 *         &lt;element ref="{}dtGMTOpened"/>
 *         &lt;element ref="{}dtGMTClosed"/>
 *         &lt;element ref="{}dtGMTTrashed"/>
 *         &lt;element ref="{}lastupdate"/>
 *         &lt;element ref="{}lastpubupdate"/>
 *         &lt;element ref="{}lastcustupdate"/>
 *         &lt;element ref="{}ctPublicUpdates"/>
 *         &lt;element ref="{}age"/>
 *         &lt;element ref="{}timetrack"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iLastReplyBy",
    "fOpenedVia",
    "mailbox",
    "fOpen",
    "xRequest",
    "sUserId",
    "fullname",
    "sLastName",
    "sEmail",
    "sPhone",
    "xPersonOpenedBy",
    "xPersonAssignedTo",
    "xStatus",
    "sCategory",
    "sTitle",
    "reqsummary",
    "lastpublicnote",
    "lastpublicnoteby",
    "dtGMTOpened",
    "dtGMTClosed",
    "dtGMTTrashed",
    "lastupdate",
    "lastpubupdate",
    "lastcustupdate",
    "ctPublicUpdates",
    "age",
    "timetrack"
})
@XmlRootElement(name = "labels")
public class Labels implements Serializable {

	private static final long serialVersionUID = 3061176266817988583L;
	
	@XmlElement(required = false)
    protected String iLastReplyBy;
    @XmlElement(required = false)
    protected String fOpenedVia;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String mailbox;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fOpen;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String xRequest;
    @XmlElement(required = false)
    protected String sUserId;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fullname;
    @XmlElement(required = false)
    protected String sLastName;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sEmail;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sPhone;
    @XmlElement(required = false)
    protected String xPersonOpenedBy;
    @XmlElement(required = false)
    protected String xPersonAssignedTo;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String xStatus;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sCategory;
    @XmlElement(required = false)
    protected String sTitle;
    @XmlElement(required = false)
    protected String reqsummary;
    @XmlElement(required = false)
    protected String lastpublicnote;
    @XmlElement(required = false)
    protected String lastpublicnoteby;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dtGMTOpened;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dtGMTClosed;
    @XmlElement(required = false)
    protected String dtGMTTrashed;
    @XmlElement(required = false)
    protected String lastupdate;
    @XmlElement(required = false)
    protected String lastpubupdate;
    @XmlElement(required = false)
    protected String lastcustupdate;
    @XmlElement(required = false)
    protected String ctPublicUpdates;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String age;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String timetrack;

    /**
     * Gets the value of the iLastReplyBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getILastReplyBy() {
        return iLastReplyBy;
    }

    /**
     * Sets the value of the iLastReplyBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setILastReplyBy(String value) {
        this.iLastReplyBy = value;
    }

    /**
     * Gets the value of the fOpenedVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOpenedVia() {
        return fOpenedVia;
    }

    /**
     * Sets the value of the fOpenedVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOpenedVia(String value) {
        this.fOpenedVia = value;
    }

    /**
     * Gets the value of the mailbox property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * Sets the value of the mailbox property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailbox(String value) {
        this.mailbox = value;
    }

    /**
     * Gets the value of the fOpen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOpen() {
        return fOpen;
    }

    /**
     * Sets the value of the fOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOpen(String value) {
        this.fOpen = value;
    }

    /**
     * Gets the value of the xRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXRequest() {
        return xRequest;
    }

    /**
     * Sets the value of the xRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXRequest(String value) {
        this.xRequest = value;
    }

    /**
     * Gets the value of the sUserId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUserId() {
        return sUserId;
    }

    /**
     * Sets the value of the sUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUserId(String value) {
        this.sUserId = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullname(String value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the sLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSLastName() {
        return sLastName;
    }

    /**
     * Sets the value of the sLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSLastName(String value) {
        this.sLastName = value;
    }

    /**
     * Gets the value of the sEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEmail() {
        return sEmail;
    }

    /**
     * Sets the value of the sEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEmail(String value) {
        this.sEmail = value;
    }

    /**
     * Gets the value of the sPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPhone() {
        return sPhone;
    }

    /**
     * Sets the value of the sPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPhone(String value) {
        this.sPhone = value;
    }

    /**
     * Gets the value of the xPersonOpenedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPersonOpenedBy() {
        return xPersonOpenedBy;
    }

    /**
     * Sets the value of the xPersonOpenedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPersonOpenedBy(String value) {
        this.xPersonOpenedBy = value;
    }

    /**
     * Gets the value of the xPersonAssignedTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPersonAssignedTo() {
        return xPersonAssignedTo;
    }

    /**
     * Sets the value of the xPersonAssignedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPersonAssignedTo(String value) {
        this.xPersonAssignedTo = value;
    }

    /**
     * Gets the value of the xStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXStatus() {
        return xStatus;
    }

    /**
     * Sets the value of the xStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXStatus(String value) {
        this.xStatus = value;
    }

    /**
     * Gets the value of the sCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCategory() {
        return sCategory;
    }

    /**
     * Sets the value of the sCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCategory(String value) {
        this.sCategory = value;
    }

    /**
     * Gets the value of the sTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTitle() {
        return sTitle;
    }

    /**
     * Sets the value of the sTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTitle(String value) {
        this.sTitle = value;
    }

    /**
     * Gets the value of the reqsummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqsummary() {
        return reqsummary;
    }

    /**
     * Sets the value of the reqsummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqsummary(String value) {
        this.reqsummary = value;
    }

    /**
     * Gets the value of the lastpublicnote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastpublicnote() {
        return lastpublicnote;
    }

    /**
     * Sets the value of the lastpublicnote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastpublicnote(String value) {
        this.lastpublicnote = value;
    }

    /**
     * Gets the value of the lastpublicnoteby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastpublicnoteby() {
        return lastpublicnoteby;
    }

    /**
     * Sets the value of the lastpublicnoteby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastpublicnoteby(String value) {
        this.lastpublicnoteby = value;
    }

    /**
     * Gets the value of the dtGMTOpened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtGMTOpened() {
        return dtGMTOpened;
    }

    /**
     * Sets the value of the dtGMTOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtGMTOpened(String value) {
        this.dtGMTOpened = value;
    }

    /**
     * Gets the value of the dtGMTClosed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtGMTClosed() {
        return dtGMTClosed;
    }

    /**
     * Sets the value of the dtGMTClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtGMTClosed(String value) {
        this.dtGMTClosed = value;
    }

    /**
     * Gets the value of the dtGMTTrashed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtGMTTrashed() {
        return dtGMTTrashed;
    }

    /**
     * Sets the value of the dtGMTTrashed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtGMTTrashed(String value) {
        this.dtGMTTrashed = value;
    }

    /**
     * Gets the value of the lastupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastupdate() {
        return lastupdate;
    }

    /**
     * Sets the value of the lastupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastupdate(String value) {
        this.lastupdate = value;
    }

    /**
     * Gets the value of the lastpubupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastpubupdate() {
        return lastpubupdate;
    }

    /**
     * Sets the value of the lastpubupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastpubupdate(String value) {
        this.lastpubupdate = value;
    }

    /**
     * Gets the value of the lastcustupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastcustupdate() {
        return lastcustupdate;
    }

    /**
     * Sets the value of the lastcustupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastcustupdate(String value) {
        this.lastcustupdate = value;
    }

    /**
     * Gets the value of the ctPublicUpdates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCtPublicUpdates() {
        return ctPublicUpdates;
    }

    /**
     * Sets the value of the ctPublicUpdates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCtPublicUpdates(String value) {
        this.ctPublicUpdates = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAge(String value) {
        this.age = value;
    }

    /**
     * Gets the value of the timetrack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimetrack() {
        return timetrack;
    }

    /**
     * Sets the value of the timetrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimetrack(String value) {
        this.timetrack = value;
    }

}
