//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:55:28 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.filter.get_column_names;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.stinkbird.helpspot.private_api.response_for.filter.get_column_names package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Reqsummary_QNAME = new QName("", "reqsummary");
    private final static QName _SPhone_QNAME = new QName("", "sPhone");
    private final static QName _FOpenedVia_QNAME = new QName("", "fOpenedVia");
    private final static QName _XPersonAssignedTo_QNAME = new QName("", "xPersonAssignedTo");
    private final static QName _DtGMTClosed_QNAME = new QName("", "dtGMTClosed");
    private final static QName _Mailbox_QNAME = new QName("", "mailbox");
    private final static QName _FOpen_QNAME = new QName("", "fOpen");
    private final static QName _Lastupdate_QNAME = new QName("", "lastupdate");
    private final static QName _Age_QNAME = new QName("", "age");
    private final static QName _ILastReplyBy_QNAME = new QName("", "iLastReplyBy");
    private final static QName _Lastpublicnoteby_QNAME = new QName("", "lastpublicnoteby");
    private final static QName _Fullname_QNAME = new QName("", "fullname");
    private final static QName _CtPublicUpdates_QNAME = new QName("", "ctPublicUpdates");
    private final static QName _XRequest_QNAME = new QName("", "xRequest");
    private final static QName _DtGMTOpened_QNAME = new QName("", "dtGMTOpened");
    private final static QName _Lastcustupdate_QNAME = new QName("", "lastcustupdate");
    private final static QName _DtGMTTrashed_QNAME = new QName("", "dtGMTTrashed");
    private final static QName _XPersonOpenedBy_QNAME = new QName("", "xPersonOpenedBy");
    private final static QName _SCategory_QNAME = new QName("", "sCategory");
    private final static QName _SEmail_QNAME = new QName("", "sEmail");
    private final static QName _Lastpubupdate_QNAME = new QName("", "lastpubupdate");
    private final static QName _SLastName_QNAME = new QName("", "sLastName");
    private final static QName _Timetrack_QNAME = new QName("", "timetrack");
    private final static QName _SUserId_QNAME = new QName("", "sUserId");
    private final static QName _STitle_QNAME = new QName("", "sTitle");
    private final static QName _Lastpublicnote_QNAME = new QName("", "lastpublicnote");
    private final static QName _XStatus_QNAME = new QName("", "xStatus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.stinkbird.helpspot.private_api.response_for.filter.get_column_names
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Labels }
     * 
     */
    public Labels createLabels() {
        return new Labels();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reqsummary")
    public JAXBElement<String> createReqsummary(String value) {
        return new JAXBElement<String>(_Reqsummary_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sPhone")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSPhone(String value) {
        return new JAXBElement<String>(_SPhone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fOpenedVia")
    public JAXBElement<String> createFOpenedVia(String value) {
        return new JAXBElement<String>(_FOpenedVia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPersonAssignedTo")
    public JAXBElement<String> createXPersonAssignedTo(String value) {
        return new JAXBElement<String>(_XPersonAssignedTo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTClosed")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDtGMTClosed(String value) {
        return new JAXBElement<String>(_DtGMTClosed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mailbox")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMailbox(String value) {
        return new JAXBElement<String>(_Mailbox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fOpen")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFOpen(String value) {
        return new JAXBElement<String>(_FOpen_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastupdate")
    public JAXBElement<String> createLastupdate(String value) {
        return new JAXBElement<String>(_Lastupdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "age")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAge(String value) {
        return new JAXBElement<String>(_Age_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iLastReplyBy")
    public JAXBElement<String> createILastReplyBy(String value) {
        return new JAXBElement<String>(_ILastReplyBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastpublicnoteby")
    public JAXBElement<String> createLastpublicnoteby(String value) {
        return new JAXBElement<String>(_Lastpublicnoteby_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fullname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFullname(String value) {
        return new JAXBElement<String>(_Fullname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ctPublicUpdates")
    public JAXBElement<String> createCtPublicUpdates(String value) {
        return new JAXBElement<String>(_CtPublicUpdates_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xRequest")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createXRequest(String value) {
        return new JAXBElement<String>(_XRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTOpened")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDtGMTOpened(String value) {
        return new JAXBElement<String>(_DtGMTOpened_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastcustupdate")
    public JAXBElement<String> createLastcustupdate(String value) {
        return new JAXBElement<String>(_Lastcustupdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTTrashed")
    public JAXBElement<String> createDtGMTTrashed(String value) {
        return new JAXBElement<String>(_DtGMTTrashed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPersonOpenedBy")
    public JAXBElement<String> createXPersonOpenedBy(String value) {
        return new JAXBElement<String>(_XPersonOpenedBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sCategory")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSCategory(String value) {
        return new JAXBElement<String>(_SCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sEmail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSEmail(String value) {
        return new JAXBElement<String>(_SEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastpubupdate")
    public JAXBElement<String> createLastpubupdate(String value) {
        return new JAXBElement<String>(_Lastpubupdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sLastName")
    public JAXBElement<String> createSLastName(String value) {
        return new JAXBElement<String>(_SLastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "timetrack")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTimetrack(String value) {
        return new JAXBElement<String>(_Timetrack_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sUserId")
    public JAXBElement<String> createSUserId(String value) {
        return new JAXBElement<String>(_SUserId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sTitle")
    public JAXBElement<String> createSTitle(String value) {
        return new JAXBElement<String>(_STitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastpublicnote")
    public JAXBElement<String> createLastpublicnote(String value) {
        return new JAXBElement<String>(_Lastpublicnote_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xStatus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createXStatus(String value) {
        return new JAXBElement<String>(_XStatus_QNAME, String.class, null, value);
    }

}
