//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:58:44 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.request.get_categories;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}xCategory"/>
 *         &lt;element ref="{}sCategory"/>
 *         &lt;element ref="{}sCategoryGroup"/>
 *         &lt;element ref="{}fDeleted"/>
 *         &lt;element ref="{}fAllowPublicSubmit"/>
 *         &lt;element ref="{}xPersonDefault"/>
 *         &lt;element ref="{}fAutoAssignTo"/>
 *         &lt;element ref="{}sPersonList"/>
 *         &lt;element ref="{}sCustomFieldList"/>
 *         &lt;element ref="{}reportingTags"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xCategory",
    "sCategory",
    "sCategoryGroup",
    "fDeleted",
    "fAllowPublicSubmit",
    "xPersonDefault",
    "fAutoAssignTo",
    "sPersonList",
    "sCustomFieldList",
    "reportingTags"
})
@XmlRootElement(name = "category")
public class Category implements Serializable {

	private static final long serialVersionUID = -7949398831202042045L;
	
	@XmlElement(required = false)
    protected BigInteger xCategory;
    @XmlElement(required = false)
    protected String sCategory;
    @XmlElement(required = false)
    protected SCategoryGroup sCategoryGroup;
    @XmlElement(required = false)
    protected BigInteger fDeleted;
    @XmlElement(required = false)
    protected BigInteger fAllowPublicSubmit;
    @XmlElement(required = false)
    protected BigInteger xPersonDefault;
    @XmlElement(required = false)
    protected BigInteger fAutoAssignTo;
    @XmlElement(required = false)
    protected SPersonList sPersonList;
    @XmlElement(required = false)
    protected SCustomFieldList sCustomFieldList;
    @XmlElement(required = false)
    protected ReportingTags reportingTags;

    /**
     * Gets the value of the xCategory property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXCategory() {
        return xCategory;
    }

    /**
     * Sets the value of the xCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXCategory(BigInteger value) {
        this.xCategory = value;
    }

    /**
     * Gets the value of the sCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCategory() {
        return sCategory;
    }

    /**
     * Sets the value of the sCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCategory(String value) {
        this.sCategory = value;
    }

    /**
     * Gets the value of the sCategoryGroup property.
     * 
     * @return
     *     possible object is
     *     {@link SCategoryGroup }
     *     
     */
    public SCategoryGroup getSCategoryGroup() {
        return sCategoryGroup;
    }

    /**
     * Sets the value of the sCategoryGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCategoryGroup }
     *     
     */
    public void setSCategoryGroup(SCategoryGroup value) {
        this.sCategoryGroup = value;
    }

    /**
     * Gets the value of the fDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFDeleted() {
        return fDeleted;
    }

    /**
     * Sets the value of the fDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFDeleted(BigInteger value) {
        this.fDeleted = value;
    }

    /**
     * Gets the value of the fAllowPublicSubmit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFAllowPublicSubmit() {
        return fAllowPublicSubmit;
    }

    /**
     * Sets the value of the fAllowPublicSubmit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFAllowPublicSubmit(BigInteger value) {
        this.fAllowPublicSubmit = value;
    }

    /**
     * Gets the value of the xPersonDefault property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXPersonDefault() {
        return xPersonDefault;
    }

    /**
     * Sets the value of the xPersonDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXPersonDefault(BigInteger value) {
        this.xPersonDefault = value;
    }

    /**
     * Gets the value of the fAutoAssignTo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFAutoAssignTo() {
        return fAutoAssignTo;
    }

    /**
     * Sets the value of the fAutoAssignTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFAutoAssignTo(BigInteger value) {
        this.fAutoAssignTo = value;
    }

    /**
     * Gets the value of the sPersonList property.
     * 
     * @return
     *     possible object is
     *     {@link SPersonList }
     *     
     */
    public SPersonList getSPersonList() {
        return sPersonList;
    }

    /**
     * Sets the value of the sPersonList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPersonList }
     *     
     */
    public void setSPersonList(SPersonList value) {
        this.sPersonList = value;
    }

    /**
     * Gets the value of the sCustomFieldList property.
     * 
     * @return
     *     possible object is
     *     {@link SCustomFieldList }
     *     
     */
    public SCustomFieldList getSCustomFieldList() {
        return sCustomFieldList;
    }

    /**
     * Sets the value of the sCustomFieldList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCustomFieldList }
     *     
     */
    public void setSCustomFieldList(SCustomFieldList value) {
        this.sCustomFieldList = value;
    }

    /**
     * Gets the value of the reportingTags property.
     * 
     * @return
     *     possible object is
     *     {@link ReportingTags }
     *     
     */
    public ReportingTags getReportingTags() {
        return reportingTags;
    }

    /**
     * Sets the value of the reportingTags property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportingTags }
     *     
     */
    public void setReportingTags(ReportingTags value) {
        this.reportingTags = value;
    }

}
