//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:58:44 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.request.get_categories;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.stinkbird.helpspot.private_api.response_for.request.get_categories package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XPersonDefault_QNAME = new QName("", "xPersonDefault");
    private final static QName _XCustomField_QNAME = new QName("", "xCustomField");
    private final static QName _XReportingTag_QNAME = new QName("", "xReportingTag");
    private final static QName _FDeleted_QNAME = new QName("", "fDeleted");
    private final static QName _XCategory_QNAME = new QName("", "xCategory");
    private final static QName _FAutoAssignTo_QNAME = new QName("", "fAutoAssignTo");
    private final static QName _AssignedRequests_QNAME = new QName("", "assigned_requests");
    private final static QName _FAllowPublicSubmit_QNAME = new QName("", "fAllowPublicSubmit");
    private final static QName _XPerson_QNAME = new QName("", "xPerson");
    private final static QName _Fullname_QNAME = new QName("", "fullname");
    private final static QName _SCategory_QNAME = new QName("", "sCategory");
    private final static QName _SReportingTag_QNAME = new QName("", "sReportingTag");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.stinkbird.helpspot.private_api.response_for.request.get_categories
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link ReportingTags }
     * 
     */
    public ReportingTags createReportingTags() {
        return new ReportingTags();
    }

    /**
     * Create an instance of {@link SCategoryGroup }
     * 
     */
    public SCategoryGroup createSCategoryGroup() {
        return new SCategoryGroup();
    }

    /**
     * Create an instance of {@link SCustomFieldList }
     * 
     */
    public SCustomFieldList createSCustomFieldList() {
        return new SCustomFieldList();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Categories }
     * 
     */
    public Categories createCategories() {
        return new Categories();
    }

    /**
     * Create an instance of {@link SPersonList }
     * 
     */
    public SPersonList createSPersonList() {
        return new SPersonList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPersonDefault")
    public JAXBElement<BigInteger> createXPersonDefault(BigInteger value) {
        return new JAXBElement<BigInteger>(_XPersonDefault_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xCustomField")
    public JAXBElement<BigInteger> createXCustomField(BigInteger value) {
        return new JAXBElement<BigInteger>(_XCustomField_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xReportingTag")
    public JAXBElement<BigInteger> createXReportingTag(BigInteger value) {
        return new JAXBElement<BigInteger>(_XReportingTag_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fDeleted")
    public JAXBElement<BigInteger> createFDeleted(BigInteger value) {
        return new JAXBElement<BigInteger>(_FDeleted_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xCategory")
    public JAXBElement<BigInteger> createXCategory(BigInteger value) {
        return new JAXBElement<BigInteger>(_XCategory_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fAutoAssignTo")
    public JAXBElement<BigInteger> createFAutoAssignTo(BigInteger value) {
        return new JAXBElement<BigInteger>(_FAutoAssignTo_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "assigned_requests")
    public JAXBElement<BigInteger> createAssignedRequests(BigInteger value) {
        return new JAXBElement<BigInteger>(_AssignedRequests_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fAllowPublicSubmit")
    public JAXBElement<BigInteger> createFAllowPublicSubmit(BigInteger value) {
        return new JAXBElement<BigInteger>(_FAllowPublicSubmit_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPerson")
    public JAXBElement<BigInteger> createXPerson(BigInteger value) {
        return new JAXBElement<BigInteger>(_XPerson_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fullname")
    public JAXBElement<String> createFullname(String value) {
        return new JAXBElement<String>(_Fullname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sCategory")
    public JAXBElement<String> createSCategory(String value) {
        return new JAXBElement<String>(_SCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sReportingTag")
    public JAXBElement<String> createSReportingTag(String value) {
        return new JAXBElement<String>(_SReportingTag_QNAME, String.class, null, value);
    }

}
