//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 02:04:29 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.timetracker.search;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.stinkbird.helpspot.private_api.response_for.timetracker.search package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DtGMTDateAdded_QNAME = new QName("", "dtGMTDateAdded");
    private final static QName _SEmail_QNAME = new QName("", "sEmail");
    private final static QName _SLastName_QNAME = new QName("", "sLastName");
    private final static QName _XTimeId_QNAME = new QName("", "xTimeId");
    private final static QName _SUserId_QNAME = new QName("", "sUserId");
    private final static QName _ISeconds_QNAME = new QName("", "iSeconds");
    private final static QName _TDescription_QNAME = new QName("", "tDescription");
    private final static QName _DtGMTDate_QNAME = new QName("", "dtGMTDate");
    private final static QName _SFirstName_QNAME = new QName("", "sFirstName");
    private final static QName _XPerson_QNAME = new QName("", "xPerson");
    private final static QName _XRequest_QNAME = new QName("", "xRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.stinkbird.helpspot.private_api.response_for.timetracker.search
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link TimeEvents }
     * 
     */
    public TimeEvents createTimeEvents() {
        return new TimeEvents();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTDateAdded")
    public JAXBElement<String> createDtGMTDateAdded(String value) {
        return new JAXBElement<String>(_DtGMTDateAdded_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sEmail")
    public JAXBElement<String> createSEmail(String value) {
        return new JAXBElement<String>(_SEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sLastName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSLastName(String value) {
        return new JAXBElement<String>(_SLastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xTimeId")
    public JAXBElement<BigInteger> createXTimeId(BigInteger value) {
        return new JAXBElement<BigInteger>(_XTimeId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sUserId")
    public JAXBElement<BigInteger> createSUserId(BigInteger value) {
        return new JAXBElement<BigInteger>(_SUserId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iSeconds")
    public JAXBElement<BigInteger> createISeconds(BigInteger value) {
        return new JAXBElement<BigInteger>(_ISeconds_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tDescription")
    public JAXBElement<String> createTDescription(String value) {
        return new JAXBElement<String>(_TDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTDate")
    public JAXBElement<String> createDtGMTDate(String value) {
        return new JAXBElement<String>(_DtGMTDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sFirstName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSFirstName(String value) {
        return new JAXBElement<String>(_SFirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPerson")
    public JAXBElement<String> createXPerson(String value) {
        return new JAXBElement<String>(_XPerson_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xRequest")
    public JAXBElement<BigInteger> createXRequest(BigInteger value) {
        return new JAXBElement<BigInteger>(_XRequest_QNAME, BigInteger.class, null, value);
    }

}
