//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:59:27 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.request.get_custom_fields;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.stinkbird.helpspot.private_api.response_for.request.get_custom_fields package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IOrder_QNAME = new QName("", "iOrder");
    private final static QName _XCustomField_QNAME = new QName("", "xCustomField");
    private final static QName _IsRequired_QNAME = new QName("", "isRequired");
    private final static QName _IsAlwaysVisible_QNAME = new QName("", "isAlwaysVisible");
    private final static QName _FieldType_QNAME = new QName("", "fieldType");
    private final static QName _Item_QNAME = new QName("", "item");
    private final static QName _IDecimalPlaces_QNAME = new QName("", "iDecimalPlaces");
    private final static QName _IsPublic_QNAME = new QName("", "isPublic");
    private final static QName _FieldName_QNAME = new QName("", "fieldName");
    private final static QName _SAjaxUrl_QNAME = new QName("", "sAjaxUrl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.stinkbird.helpspot.private_api.response_for.request.get_custom_fields
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListItems }
     * 
     */
    public ListItems createListItems() {
        return new ListItems();
    }

    /**
     * Create an instance of {@link SRegex }
     * 
     */
    public SRegex createSRegex() {
        return new SRegex();
    }

    /**
     * Create an instance of {@link STxtSize }
     * 
     */
    public STxtSize createSTxtSize() {
        return new STxtSize();
    }

    /**
     * Create an instance of {@link LrgTextRows }
     * 
     */
    public LrgTextRows createLrgTextRows() {
        return new LrgTextRows();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Customfields }
     * 
     */
    public Customfields createCustomfields() {
        return new Customfields();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iOrder")
    public JAXBElement<BigInteger> createIOrder(BigInteger value) {
        return new JAXBElement<BigInteger>(_IOrder_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xCustomField")
    public JAXBElement<BigInteger> createXCustomField(BigInteger value) {
        return new JAXBElement<BigInteger>(_XCustomField_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isRequired")
    public JAXBElement<BigInteger> createIsRequired(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsRequired_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isAlwaysVisible")
    public JAXBElement<BigInteger> createIsAlwaysVisible(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsAlwaysVisible_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFieldType(String value) {
        return new JAXBElement<String>(_FieldType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "item")
    public JAXBElement<String> createItem(String value) {
        return new JAXBElement<String>(_Item_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iDecimalPlaces")
    public JAXBElement<BigInteger> createIDecimalPlaces(BigInteger value) {
        return new JAXBElement<BigInteger>(_IDecimalPlaces_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isPublic")
    public JAXBElement<BigInteger> createIsPublic(BigInteger value) {
        return new JAXBElement<BigInteger>(_IsPublic_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fieldName")
    public JAXBElement<String> createFieldName(String value) {
        return new JAXBElement<String>(_FieldName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sAjaxUrl")
    public JAXBElement<String> createSAjaxUrl(String value) {
        return new JAXBElement<String>(_SAjaxUrl_QNAME, String.class, null, value);
    }

}
