//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:57:58 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.request.get;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}sFileMimeType"/>
 *         &lt;element ref="{}sFilename"/>
 *         &lt;element ref="{}xDocumentId"/>
 *         &lt;element ref="{}public_url"/>
 *         &lt;element ref="{}private_url"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sFileMimeType",
    "sFilename",
    "xDocumentId",
    "publicUrl",
    "privateUrl"
})
@XmlRootElement(name = "file")
public class File {

    @XmlElement(required = false)
    protected String sFileMimeType;
    @XmlElement(required = false)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sFilename;
    @XmlElement(required = false)
    protected BigInteger xDocumentId;
    @XmlElement(name = "public_url", required = false)
    @XmlSchemaType(name = "anyURI")
    protected String publicUrl;
    @XmlElement(name = "private_url", required = false)
    @XmlSchemaType(name = "anyURI")
    protected String privateUrl;

    /**
     * Gets the value of the sFileMimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSFileMimeType() {
        return sFileMimeType;
    }

    /**
     * Sets the value of the sFileMimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSFileMimeType(String value) {
        this.sFileMimeType = value;
    }

    /**
     * Gets the value of the sFilename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSFilename() {
        return sFilename;
    }

    /**
     * Sets the value of the sFilename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSFilename(String value) {
        this.sFilename = value;
    }

    /**
     * Gets the value of the xDocumentId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXDocumentId() {
        return xDocumentId;
    }

    /**
     * Sets the value of the xDocumentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXDocumentId(BigInteger value) {
        this.xDocumentId = value;
    }

    /**
     * Gets the value of the publicUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicUrl() {
        return publicUrl;
    }

    /**
     * Sets the value of the publicUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicUrl(String value) {
        this.publicUrl = value;
    }

    /**
     * Gets the value of the privateUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateUrl() {
        return privateUrl;
    }

    /**
     * Sets the value of the privateUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateUrl(String value) {
        this.privateUrl = value;
    }

}
