//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.12 at 05:13:17 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.request.get;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.stinkbird.helpspot.private_api.response_for.request.get package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FPublic_QNAME = new QName("", "fPublic");
    private final static QName _TEmailHeaders_QNAME = new QName("", "tEmailHeaders");
    private final static QName _FNoteIsHTML_QNAME = new QName("", "fNoteIsHTML");
    private final static QName _SPhone_QNAME = new QName("", "sPhone");
    private final static QName _SFileMimeType_QNAME = new QName("", "sFileMimeType");
    private final static QName _FOpenedVia_QNAME = new QName("", "fOpenedVia");
    private final static QName _SFilename_QNAME = new QName("", "sFilename");
    private final static QName _XPersonAssignedTo_QNAME = new QName("", "xPersonAssignedTo");
    private final static QName _DtGMTClosed_QNAME = new QName("", "dtGMTClosed");
    private final static QName _FOpen_QNAME = new QName("", "fOpen");
    private final static QName _FMergedFromRequest_QNAME = new QName("", "fMergedFromRequest");
    private final static QName _DtGMTChange_QNAME = new QName("", "dtGMTChange");
    private final static QName _ILastReplyBy_QNAME = new QName("", "iLastReplyBy");
    private final static QName _XCategory_QNAME = new QName("", "xCategory");
    private final static QName _Fullname_QNAME = new QName("", "fullname");
    private final static QName _XRequest_QNAME = new QName("", "xRequest");
    private final static QName _DtGMTOpened_QNAME = new QName("", "dtGMTOpened");
    private final static QName _DtGMTTrashed_QNAME = new QName("", "dtGMTTrashed");
    private final static QName _XOpenedViaId_QNAME = new QName("", "xOpenedViaId");
    private final static QName _XPersonOpenedBy_QNAME = new QName("", "xPersonOpenedBy");
    private final static QName _XPerson_QNAME = new QName("", "xPerson");
    private final static QName _PublicUrl_QNAME = new QName("", "public_url");
    private final static QName _TLog_QNAME = new QName("", "tLog");
    private final static QName _FTrash_QNAME = new QName("", "fTrash");
    private final static QName _SEmail_QNAME = new QName("", "sEmail");
    private final static QName _XDocumentId_QNAME = new QName("", "xDocumentId");
    private final static QName _SLastName_QNAME = new QName("", "sLastName");
    private final static QName _FUrgent_QNAME = new QName("", "fUrgent");
    private final static QName _P_QNAME = new QName("", "p");
    private final static QName _SUserId_QNAME = new QName("", "sUserId");
    private final static QName _PrivateUrl_QNAME = new QName("", "private_url");
    private final static QName _STitle_QNAME = new QName("", "sTitle");
    private final static QName _FInitial_QNAME = new QName("", "fInitial");
    private final static QName _SFirstName_QNAME = new QName("", "sFirstName");
    private final static QName _SRequestPassword_QNAME = new QName("", "sRequestPassword");
    private final static QName _XRequestHistory_QNAME = new QName("", "xRequestHistory");
    private final static QName _XStatus_QNAME = new QName("", "xStatus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.stinkbird.helpspot.private_api.response_for.request.get
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link Files }
     * 
     */
    public Files createFiles() {
        return new Files();
    }

    /**
     * Create an instance of {@link TNote }
     * 
     */
    public TNote createTNote() {
        return new TNote();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link RequestHistory }
     * 
     */
    public RequestHistory createRequestHistory() {
        return new RequestHistory();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fPublic")
    public JAXBElement<BigInteger> createFPublic(BigInteger value) {
        return new JAXBElement<BigInteger>(_FPublic_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tEmailHeaders")
    public JAXBElement<String> createTEmailHeaders(String value) {
        return new JAXBElement<String>(_TEmailHeaders_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fNoteIsHTML")
    public JAXBElement<BigInteger> createFNoteIsHTML(BigInteger value) {
        return new JAXBElement<BigInteger>(_FNoteIsHTML_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sPhone")
    public JAXBElement<String> createSPhone(String value) {
        return new JAXBElement<String>(_SPhone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sFileMimeType")
    public JAXBElement<String> createSFileMimeType(String value) {
        return new JAXBElement<String>(_SFileMimeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fOpenedVia")
    public JAXBElement<String> createFOpenedVia(String value) {
        return new JAXBElement<String>(_FOpenedVia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sFilename")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSFilename(String value) {
        return new JAXBElement<String>(_SFilename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPersonAssignedTo")
    public JAXBElement<String> createXPersonAssignedTo(String value) {
        return new JAXBElement<String>(_XPersonAssignedTo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTClosed")
    public JAXBElement<String> createDtGMTClosed(String value) {
        return new JAXBElement<String>(_DtGMTClosed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fOpen")
    public JAXBElement<BigInteger> createFOpen(BigInteger value) {
        return new JAXBElement<BigInteger>(_FOpen_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fMergedFromRequest")
    public JAXBElement<BigInteger> createFMergedFromRequest(BigInteger value) {
        return new JAXBElement<BigInteger>(_FMergedFromRequest_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTChange")
    public JAXBElement<String> createDtGMTChange(String value) {
        return new JAXBElement<String>(_DtGMTChange_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "iLastReplyBy")
    public JAXBElement<String> createILastReplyBy(String value) {
        return new JAXBElement<String>(_ILastReplyBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xCategory")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createXCategory(String value) {
        return new JAXBElement<String>(_XCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fullname")
    public JAXBElement<String> createFullname(String value) {
        return new JAXBElement<String>(_Fullname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xRequest")
    public JAXBElement<BigInteger> createXRequest(BigInteger value) {
        return new JAXBElement<BigInteger>(_XRequest_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTOpened")
    public JAXBElement<String> createDtGMTOpened(String value) {
        return new JAXBElement<String>(_DtGMTOpened_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dtGMTTrashed")
    public JAXBElement<String> createDtGMTTrashed(String value) {
        return new JAXBElement<String>(_DtGMTTrashed_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xOpenedViaId")
    public JAXBElement<BigInteger> createXOpenedViaId(BigInteger value) {
        return new JAXBElement<BigInteger>(_XOpenedViaId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPersonOpenedBy")
    public JAXBElement<String> createXPersonOpenedBy(String value) {
        return new JAXBElement<String>(_XPersonOpenedBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xPerson")
    public JAXBElement<String> createXPerson(String value) {
        return new JAXBElement<String>(_XPerson_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "public_url")
    public JAXBElement<String> createPublicUrl(String value) {
        return new JAXBElement<String>(_PublicUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "tLog")
    public JAXBElement<String> createTLog(String value) {
        return new JAXBElement<String>(_TLog_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fTrash")
    public JAXBElement<BigInteger> createFTrash(BigInteger value) {
        return new JAXBElement<BigInteger>(_FTrash_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sEmail")
    public JAXBElement<String> createSEmail(String value) {
        return new JAXBElement<String>(_SEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xDocumentId")
    public JAXBElement<BigInteger> createXDocumentId(BigInteger value) {
        return new JAXBElement<BigInteger>(_XDocumentId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sLastName")
    public JAXBElement<String> createSLastName(String value) {
        return new JAXBElement<String>(_SLastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fUrgent")
    public JAXBElement<BigInteger> createFUrgent(BigInteger value) {
        return new JAXBElement<BigInteger>(_FUrgent_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "p")
    public JAXBElement<String> createP(String value) {
        return new JAXBElement<String>(_P_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sUserId")
    public JAXBElement<BigInteger> createSUserId(BigInteger value) {
        return new JAXBElement<BigInteger>(_SUserId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "private_url")
    public JAXBElement<String> createPrivateUrl(String value) {
        return new JAXBElement<String>(_PrivateUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sTitle")
    public JAXBElement<String> createSTitle(String value) {
        return new JAXBElement<String>(_STitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fInitial")
    public JAXBElement<BigInteger> createFInitial(BigInteger value) {
        return new JAXBElement<BigInteger>(_FInitial_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sFirstName")
    public JAXBElement<String> createSFirstName(String value) {
        return new JAXBElement<String>(_SFirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sRequestPassword")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSRequestPassword(String value) {
        return new JAXBElement<String>(_SRequestPassword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xRequestHistory")
    public JAXBElement<BigInteger> createXRequestHistory(BigInteger value) {
        return new JAXBElement<BigInteger>(_XRequestHistory_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "xStatus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createXStatus(String value) {
        return new JAXBElement<String>(_XStatus_QNAME, String.class, null, value);
    }

}
