//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 01:57:58 PM CDT 
//


package com.github.stinkbird.helpspot.private_api.response_for.request.get;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}xRequest"/>
 *         &lt;element ref="{}fOpenedVia"/>
 *         &lt;element ref="{}xOpenedViaId"/>
 *         &lt;element ref="{}xPersonOpenedBy"/>
 *         &lt;element ref="{}xPersonAssignedTo"/>
 *         &lt;element ref="{}fOpen"/>
 *         &lt;element ref="{}xStatus"/>
 *         &lt;element ref="{}fUrgent"/>
 *         &lt;element ref="{}xCategory"/>
 *         &lt;element ref="{}dtGMTOpened"/>
 *         &lt;element ref="{}dtGMTClosed"/>
 *         &lt;element ref="{}sRequestPassword"/>
 *         &lt;element ref="{}sTitle"/>
 *         &lt;element ref="{}sUserId"/>
 *         &lt;element ref="{}sFirstName"/>
 *         &lt;element ref="{}sLastName"/>
 *         &lt;element ref="{}sEmail"/>
 *         &lt;element ref="{}sPhone"/>
 *         &lt;element ref="{}iLastReplyBy"/>
 *         &lt;element ref="{}fTrash"/>
 *         &lt;element ref="{}dtGMTTrashed"/>
 *         &lt;element ref="{}fullname"/>
 *         &lt;element ref="{}request_history"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xRequest",
    "fOpenedVia",
    "xOpenedViaId",
    "xPersonOpenedBy",
    "xPersonAssignedTo",
    "fOpen",
    "xStatus",
    "fUrgent",
    "xCategory",
    "dtGMTOpened",
    "dtGMTClosed",
    "sRequestPassword",
    "sTitle",
    "sUserId",
    "sFirstName",
    "sLastName",
    "sEmail",
    "sPhone",
    "iLastReplyBy",
    "fTrash",
    "dtGMTTrashed",
    "fullname",
    "requestHistory"
})
@XmlRootElement(name = "request")
public class Request {

    @XmlElement(required = true)
    protected BigInteger xRequest;
    @XmlElement(required = true)
    protected String fOpenedVia;
    @XmlElement(required = true)
    protected BigInteger xOpenedViaId;
    @XmlElement(required = true)
    protected XPersonOpenedBy xPersonOpenedBy;
    @XmlElement(required = true)
    protected String xPersonAssignedTo;
    @XmlElement(required = true)
    protected BigInteger fOpen;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String xStatus;
    @XmlElement(required = true)
    protected BigInteger fUrgent;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String xCategory;
    @XmlElement(required = true)
    protected String dtGMTOpened;
    @XmlElement(required = true)
    protected DtGMTClosed dtGMTClosed;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sRequestPassword;
    @XmlElement(required = true)
    protected STitle sTitle;
    @XmlElement(required = true)
    protected BigInteger sUserId;
    @XmlElement(required = true)
    protected SFirstName sFirstName;
    @XmlElement(required = true)
    protected SLastName sLastName;
    @XmlElement(required = true)
    protected SEmail sEmail;
    @XmlElement(required = true)
    protected SPhone sPhone;
    @XmlElement(required = true)
    protected String iLastReplyBy;
    @XmlElement(required = true)
    protected BigInteger fTrash;
    @XmlElement(required = true)
    protected DtGMTTrashed dtGMTTrashed;
    @XmlElement(required = true)
    protected Fullname fullname;
    @XmlElement(name = "request_history", required = true)
    protected RequestHistory requestHistory;

    /**
     * Gets the value of the xRequest property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXRequest() {
        return xRequest;
    }

    /**
     * Sets the value of the xRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXRequest(BigInteger value) {
        this.xRequest = value;
    }

    /**
     * Gets the value of the fOpenedVia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOpenedVia() {
        return fOpenedVia;
    }

    /**
     * Sets the value of the fOpenedVia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOpenedVia(String value) {
        this.fOpenedVia = value;
    }

    /**
     * Gets the value of the xOpenedViaId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXOpenedViaId() {
        return xOpenedViaId;
    }

    /**
     * Sets the value of the xOpenedViaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXOpenedViaId(BigInteger value) {
        this.xOpenedViaId = value;
    }

    /**
     * Gets the value of the xPersonOpenedBy property.
     * 
     * @return
     *     possible object is
     *     {@link XPersonOpenedBy }
     *     
     */
    public XPersonOpenedBy getXPersonOpenedBy() {
        return xPersonOpenedBy;
    }

    /**
     * Sets the value of the xPersonOpenedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link XPersonOpenedBy }
     *     
     */
    public void setXPersonOpenedBy(XPersonOpenedBy value) {
        this.xPersonOpenedBy = value;
    }

    /**
     * Gets the value of the xPersonAssignedTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPersonAssignedTo() {
        return xPersonAssignedTo;
    }

    /**
     * Sets the value of the xPersonAssignedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPersonAssignedTo(String value) {
        this.xPersonAssignedTo = value;
    }

    /**
     * Gets the value of the fOpen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFOpen() {
        return fOpen;
    }

    /**
     * Sets the value of the fOpen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFOpen(BigInteger value) {
        this.fOpen = value;
    }

    /**
     * Gets the value of the xStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXStatus() {
        return xStatus;
    }

    /**
     * Sets the value of the xStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXStatus(String value) {
        this.xStatus = value;
    }

    /**
     * Gets the value of the fUrgent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFUrgent() {
        return fUrgent;
    }

    /**
     * Sets the value of the fUrgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFUrgent(BigInteger value) {
        this.fUrgent = value;
    }

    /**
     * Gets the value of the xCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCategory() {
        return xCategory;
    }

    /**
     * Sets the value of the xCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCategory(String value) {
        this.xCategory = value;
    }

    /**
     * Gets the value of the dtGMTOpened property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDtGMTOpened() {
        return dtGMTOpened;
    }

    /**
     * Sets the value of the dtGMTOpened property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDtGMTOpened(String value) {
        this.dtGMTOpened = value;
    }

    /**
     * Gets the value of the dtGMTClosed property.
     * 
     * @return
     *     possible object is
     *     {@link DtGMTClosed }
     *     
     */
    public DtGMTClosed getDtGMTClosed() {
        return dtGMTClosed;
    }

    /**
     * Sets the value of the dtGMTClosed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtGMTClosed }
     *     
     */
    public void setDtGMTClosed(DtGMTClosed value) {
        this.dtGMTClosed = value;
    }

    /**
     * Gets the value of the sRequestPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRequestPassword() {
        return sRequestPassword;
    }

    /**
     * Sets the value of the sRequestPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRequestPassword(String value) {
        this.sRequestPassword = value;
    }

    /**
     * Gets the value of the sTitle property.
     * 
     * @return
     *     possible object is
     *     {@link STitle }
     *     
     */
    public STitle getSTitle() {
        return sTitle;
    }

    /**
     * Sets the value of the sTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link STitle }
     *     
     */
    public void setSTitle(STitle value) {
        this.sTitle = value;
    }

    /**
     * Gets the value of the sUserId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSUserId() {
        return sUserId;
    }

    /**
     * Sets the value of the sUserId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSUserId(BigInteger value) {
        this.sUserId = value;
    }

    /**
     * Gets the value of the sFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link SFirstName }
     *     
     */
    public SFirstName getSFirstName() {
        return sFirstName;
    }

    /**
     * Sets the value of the sFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFirstName }
     *     
     */
    public void setSFirstName(SFirstName value) {
        this.sFirstName = value;
    }

    /**
     * Gets the value of the sLastName property.
     * 
     * @return
     *     possible object is
     *     {@link SLastName }
     *     
     */
    public SLastName getSLastName() {
        return sLastName;
    }

    /**
     * Sets the value of the sLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SLastName }
     *     
     */
    public void setSLastName(SLastName value) {
        this.sLastName = value;
    }

    /**
     * Gets the value of the sEmail property.
     * 
     * @return
     *     possible object is
     *     {@link SEmail }
     *     
     */
    public SEmail getSEmail() {
        return sEmail;
    }

    /**
     * Sets the value of the sEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SEmail }
     *     
     */
    public void setSEmail(SEmail value) {
        this.sEmail = value;
    }

    /**
     * Gets the value of the sPhone property.
     * 
     * @return
     *     possible object is
     *     {@link SPhone }
     *     
     */
    public SPhone getSPhone() {
        return sPhone;
    }

    /**
     * Sets the value of the sPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPhone }
     *     
     */
    public void setSPhone(SPhone value) {
        this.sPhone = value;
    }

    /**
     * Gets the value of the iLastReplyBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getILastReplyBy() {
        return iLastReplyBy;
    }

    /**
     * Sets the value of the iLastReplyBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setILastReplyBy(String value) {
        this.iLastReplyBy = value;
    }

    /**
     * Gets the value of the fTrash property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFTrash() {
        return fTrash;
    }

    /**
     * Sets the value of the fTrash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFTrash(BigInteger value) {
        this.fTrash = value;
    }

    /**
     * Gets the value of the dtGMTTrashed property.
     * 
     * @return
     *     possible object is
     *     {@link DtGMTTrashed }
     *     
     */
    public DtGMTTrashed getDtGMTTrashed() {
        return dtGMTTrashed;
    }

    /**
     * Sets the value of the dtGMTTrashed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtGMTTrashed }
     *     
     */
    public void setDtGMTTrashed(DtGMTTrashed value) {
        this.dtGMTTrashed = value;
    }

    /**
     * Gets the value of the fullname property.
     * 
     * @return
     *     possible object is
     *     {@link Fullname }
     *     
     */
    public Fullname getFullname() {
        return fullname;
    }

    /**
     * Sets the value of the fullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fullname }
     *     
     */
    public void setFullname(Fullname value) {
        this.fullname = value;
    }

    /**
     * Gets the value of the requestHistory property.
     * 
     * @return
     *     possible object is
     *     {@link RequestHistory }
     *     
     */
    public RequestHistory getRequestHistory() {
        return requestHistory;
    }

    /**
     * Sets the value of the requestHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestHistory }
     *     
     */
    public void setRequestHistory(RequestHistory value) {
        this.requestHistory = value;
    }

}
